FROM eclipse-temurin:17-jre-alpine

WORKDIR /app

COPY cola-demo-gateway/target/*.jar app.jar

RUN addgroup -S app && adduser -S app -G app

RUN chown -R app:app /app

USER app:app

EXPOSE 8080

HEALTHCHECK --interval=30s --timeout=5s --retries=3 \
  CMD wget -qO- http://localhost:8080/actuator/health || exit 1

ENTRYPOINT ["java", \
  "-XX:+UseG1GC", \
  "-XX:MaxRAMPercentage=75.0", \
  "-Djava.security.egd=file:/dev/./urandom", \
  "-jar", "app.jar"]
